---
# handlers file for mapr_hbaseindexer

- name: restart hbase regionservers
  sudo_user: '{{mapr_admin_username}}'
  command: maprcli node services -action restart -name hbregionserver -filter csvc==hbregionserver

